/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 c:\dev\three-next\media\console.glb -o c:\dev\three-next\media\console.tsx --types 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve: THREE.Mesh
    NurbsPath001: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
    Plane_4: THREE.Mesh
    Plane_5: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    Plane005: THREE.Mesh
    Plane006: THREE.Mesh
    Plane008_1: THREE.Mesh
    Plane008_2: THREE.Mesh
    Plane008: THREE.Mesh
    Plane009: THREE.Mesh
    Plane010: THREE.Mesh
    Plane011: THREE.Mesh
    Plane012: THREE.Mesh
    Plane013: THREE.Mesh
    Plane014: THREE.Mesh
    Plane019_1: THREE.Mesh
    Plane019_2: THREE.Mesh
    Plane016: THREE.Mesh
    Plane017: THREE.Mesh
    Plane019: THREE.Mesh
    Plane020: THREE.Mesh
    Text: THREE.Mesh
  }
  materials: {
    ['Material.009']: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    hole: THREE.MeshPhysicalMaterial
    ['rog logo.001']: THREE.MeshStandardMaterial
    ['rog logo']: THREE.MeshStandardMaterial
    ['rog logo.002']: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    ['screen one']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['screen two']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function ConsoleModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/console.glb')as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={1}>
        <mesh geometry={nodes.Curve.geometry} material={materials['Material.009']} position={[0.93, -0.104, -0.04]} rotation={[2.565, -0.358, -1.364]} scale={0.072} />
        <mesh geometry={nodes.NurbsPath001.geometry} material={materials.white} position={[0, 0.225, 0.137]} scale={0.5} />
        <group position={[0, 0.228, 0.075]} scale={0.5}>
          <mesh geometry={nodes.Plane_1.geometry} material={materials.white} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials.hole} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials['rog logo.001']} />
          <mesh geometry={nodes.Plane_4.geometry} material={materials['rog logo']} />
          <mesh geometry={nodes.Plane_5.geometry} material={materials['rog logo.002']} />
        </group>
        <group position={[0, 0.228, 0.075]} scale={0.5}>
          <mesh geometry={nodes.Plane001_1.geometry} material={materials.black} />
          <mesh geometry={nodes.Plane001_2.geometry} material={materials.black} />
        </group>
        <group position={[0, 0.228, 0.075]} scale={0.5}>
          <mesh geometry={nodes.Plane002_1.geometry} material={materials['screen one']} />
          <mesh geometry={nodes.Plane002_2.geometry} material={materials['screen one']} />
        </group>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[-1.559, 0.417, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[0, 0.228, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane005.geometry} material={materials['Material.002']} position={[0, 0.228, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[0, 0.037, 0.075]} scale={0.5} />
        <group position={[-1.559, 0.416, 0.075]} scale={0.5}>
          <mesh geometry={nodes.Plane008_1.geometry} material={materials['screen one']} />
          <mesh geometry={nodes.Plane008_2.geometry} material={materials['screen one']} />
        </group>
        <mesh geometry={nodes.Plane008.geometry} material={materials['Material.001']} position={[-1.561, 0.225, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.005']} position={[0, 0.228, 0.076]} scale={0.5} />
        <mesh geometry={nodes.Plane010.geometry} material={materials['Material.001']} position={[0, 0.214, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane011.geometry} material={materials['Material.001']} position={[0, 0.214, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane012.geometry} material={materials['Material.001']} position={[0.723, 0.279, -0.092]} rotation={[Math.PI / 2, 0, -3.079]} scale={0.093} />
        <mesh geometry={nodes.Plane013.geometry} material={materials['Material.001']} position={[-0.731, 0.279, -0.092]} rotation={[-Math.PI / 2, 0, -3.079]} scale={-0.093} />
        <mesh geometry={nodes.Plane014.geometry} material={materials['Material.001']} position={[0, 0.214, 0.075]} rotation={[-Math.PI, 0, 0]} scale={-0.5} />
        <group position={[0, 0.228, 0.071]} rotation={[Math.PI / 2, 0, 0]} scale={0.499}>
          <mesh geometry={nodes.Plane019_1.geometry} material={materials['screen one']} />
          <mesh geometry={nodes.Plane019_2.geometry} material={materials['screen two']} />
        </group>
        <mesh geometry={nodes.Plane016.geometry} material={materials['Material.001']} position={[0, 0.214, 0.075]} rotation={[-Math.PI, 0, 0]} scale={-0.5} />
        <mesh geometry={nodes.Plane017.geometry} material={materials.white} position={[0, 0.228, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane019.geometry} material={materials.white} position={[0, 0.228, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Plane020.geometry} material={materials.white} position={[0, 0.228, 0.075]} scale={0.5} />
        <mesh geometry={nodes.Text.geometry} material={materials['Material.007']} position={[-0.065, -0.138, 0.077]} rotation={[1.568, 0, 0]} scale={0.027} />
      </group>
    </group>
  )
}

useGLTF.preload('/console.glb')
